### PR TITLE
Add "with-" enhancers, deprecate "use-" enhancers

### LINKED ISSUE #322: Use withFoo(history) enhancers
@mjackson 

This came up earlier, wanted to run it by you before I code it up – I think we should switch to e.g. `withBasename(history, basename)` instead of `useBasename(createHistory)({ basename })`.

This will make it easier to enhance e.g. the default `browserHistory` coming out of React Router, and is just otherwise a simpler API.

### PR DESCRIPTION
**Pull request by taion**
Closes #322

### CODE REVIEW

**Comment by taion** [comment]
I lumped in some warning-related test setup, since I want to assert on the deprecation warnings.

You'll want `?w=1` for the diffs on the tests to make sense. They look a bit messy but it was the best way I could think of to use the same tests for both "use-" and "with-" enhancers.

**Comment by taion** [comment]
The tests are probably failing because of https://github.com/ReactTraining/history/issues/291. 😑

**Comment by taion** [comment]
Rebased

**Comment by taion** [comment]
Any update here?

**Comment by mjackson** [comment]
Thanks for taking this on, @taion, and my apologies for not getting around to it sooner.

The future of this library is to just ditch the whole `use*` pattern entirely. I wouldn't be entirely opposed if you wanted to cut a 3.x release with this work in it, but I don't see the point. Most of the work for v4 is already on its way.

**Pull request closed without merging**
