### PR TITLE
Fix basename normalization

### PR DESCRIPTION
**Pull request by taion**
I'm opening this against v2.x because that's where the repro is. This should be easy to port to v3.x.

This address the issue @MoOx and others reported at https://github.com/reactjs/react-router/issues/3184#issuecomment-225448418 and elsewhere.

When using a basename with a trailing slash in React Router, along with transition hooks, when you try to push a pathname of '/', the `listenBefore` hooks on the history will fire. This will call `addBasename` from the `useBasename` enhancer, which will mutate the location object in place.

This causes problems with the basename has a trailing slash. Suppose the basename is "/" and the full pathname is also "/". The logic in `addBasename` will set up the location object such that it has `{ basename: '/', pathname: '/' }`. `createBrowserHistory` at https://github.com/ReactTraining/history/blob/v2.1.2/modules/createBrowserHistory.js#L79 will compute a `path` of `//` by concatenating `basename` and `pathname`, which will cause problems.

This PR resolves this issue by not mutating the input `location` object in `addBasename` when adding the basename.

It also adds a few minor cleanups:
- Normalize the basename once, up front, instead of doing it every time in `prependBasename`
- Rearrange the code in `addBasename` a little bit to put the guard conditions first

### CODE REVIEW

**Comment by taion** [comment]
@MoOx I can't seem to get Phenomic to point at my custom build of history. Can you check that this resolves your issue? I think CI is failing because of #291.

**Comment by mjackson** [comment]
I restarted the tests.

**Comment by taion** [comment]
I think the v2.x test suite is just going to consistently fail unless we either cut down the number test cases or drop the Safari browsers. Or maybe test against older versions of Safari?

**Comment by mjackson** [comment]
>  maybe test against older versions of Safari?

Sure, feel free to take that approach to get this work merged into 2.x.

**Comment by mjackson** [comment]
Looks like this has stalled. Please re-open if you still want to get it merged.

**Pull request closed without merging**
