### PR TITLE
Added fallback for disabled sessionStorage

### PR DESCRIPTION
**Pull request by jaxxreal**
Some users browse the Internet with disabled sessionStorage, and polyfill can't resolve such issue. That's the main reason for this pull request.

### CODE REVIEW

**Comment by taion** [comment]
Are you sure this works? I thought disabled session storage most often led to quote exceeded exceptions, not `window.sessionStorage` not being available.

**Comment by jaxxreal** [comment]
Yeah, I'm sure. In my case users use specific browsers or add-ons which define `window.sessionStorage` as `null`, and for such case my solution works as well.

**Comment by taion** [comment]
I'm not opposed to this in principle as a fallback for e.g. Safari private mode where there is no session storage period, but the fallback should be broader, and we should have tests.

**Comment by jaxxreal** [comment]
Ok, I will add test case for nulled sessionStorage.

**Comment by taion** [comment]
Session storage has different persistence semantics, and in fact they are the correct ones for history state storage.

**Comment by jaxxreal** [comment]
How about cross-browser compatibility? It's correct, but what does it mean if part of users of end product can't use it in some cases?

**Comment by taion** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage#Browser_compatibility

**Comment by jaxxreal** [comment]
Sorry, but your link don't answer on my second question.

**Comment by taion** [comment]
Can you elaborate on which browsers you are working with that do not provide session storage at all?

**Comment by jaxxreal** [comment]
FF 45.0 with `dom.storage.enabled = false` which set over `about:config` page.

**Comment by taion** [comment]
Interesting. It's not clear to me that we get much out of polyfilling session storage in this case. It's probably sufficient to just guard against the non-existence of session storage before attempting to use it.

**Comment by jaxxreal** [comment]
I don't ask you to do something else than just apply my request. It works and pass all yours test cases. If problem in another moment, could you clarify me?

**Comment by taion** [comment]
I'm saying that the fallback for `window.sessionStorage` not being available should probably be to just return early in both of those methods, rather than trying to polyfill.

**Comment by mjackson** [comment]
We can't polyfill `window.sessionStorage` with a hash in memory. It's not the same thing.

**Comment by taion** [comment]
@mjackson I agree there, but it seems not ideal to have an uncaught exception if session storagei s disabled. Doesn't that kill the transition entirely?

**Comment by jaxxreal** [comment]
I can't got your position in this question, guys. Why don't provide history functionality for browsers with disabled sessionStorage? I don't say about ie6, but about modern ones with stricter security options.

**Pull request closed without merging**
